const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('amazonControl', {
  submitTask: (payload) => ipcRenderer.invoke('amazon:submitTask', payload),
  listTasks: () => ipcRenderer.invoke('amazon:listTasks'),
  getTask: (taskId) => ipcRenderer.invoke('amazon:getTask', taskId),
  importCsv: (moduleKey, filePath) => ipcRenderer.invoke('amazon:importCsv', moduleKey, filePath),
  exportTask: (taskId, format = 'json') => ipcRenderer.invoke('amazon:exportTask', taskId, format),
  getAppState: () => ipcRenderer.invoke('amazon:getAppState'),
  listApiConnections: () => ipcRenderer.invoke('amazon:listApiConnections'),
  saveApiConnection: (payload) => ipcRenderer.invoke('amazon:saveApiConnection', payload),
  deleteApiConnection: (id) => ipcRenderer.invoke('amazon:deleteApiConnection', id),
  testApiConnection: (id) => ipcRenderer.invoke('amazon:testApiConnection', id),
  syncApiConnection: (id) => ipcRenderer.invoke('amazon:syncApiConnection', id),
  listDataImports: () => ipcRenderer.invoke('amazon:listDataImports'),
  saveDataImport: (payload) => ipcRenderer.invoke('amazon:saveDataImport', payload),
  deleteDataImport: (id) => ipcRenderer.invoke('amazon:deleteDataImport', id),
  previewDataSource: (payload) => ipcRenderer.invoke('amazon:previewDataSource', payload),
  listProjects: () => ipcRenderer.invoke('amazon:listProjects'),
  saveProject: (payload) => ipcRenderer.invoke('amazon:saveProject', payload),
  deleteProject: (id) => ipcRenderer.invoke('amazon:deleteProject', id),
  listApprovals: () => ipcRenderer.invoke('amazon:listApprovals'),
  listActionDrafts: () => ipcRenderer.invoke('amazon:listActionDrafts'),
  listExecutionQueue: () => ipcRenderer.invoke('amazon:listExecutionQueue'),
  listSkills: () => ipcRenderer.invoke('amazon:listSkills'),
  discoverSkills: (filters = {}) => ipcRenderer.invoke('amazon:discoverSkills', filters),
  saveSkill: (payload) => ipcRenderer.invoke('amazon:saveSkill', payload),
  deleteSkill: (id) => ipcRenderer.invoke('amazon:deleteSkill', id),
  listTools: () => ipcRenderer.invoke('amazon:listTools'),
  saveTool: (payload) => ipcRenderer.invoke('amazon:saveTool', payload),
  deleteTool: (id) => ipcRenderer.invoke('amazon:deleteTool', id),
  runTool: (payload) => ipcRenderer.invoke('amazon:runTool', payload),
  listToolRuns: () => ipcRenderer.invoke('amazon:listToolRuns'),
  listListingDrafts: () => ipcRenderer.invoke('amazon:listListingDrafts'),
  saveListingDraft: (payload) => ipcRenderer.invoke('amazon:saveListingDraft', payload),
  deleteListingDraft: (id) => ipcRenderer.invoke('amazon:deleteListingDraft', id),
  transitionListingDraft: (id, status) => ipcRenderer.invoke('amazon:transitionListingDraft', id, status),
  exportListingDraftCsv: (id) => ipcRenderer.invoke('amazon:exportListingDraftCsv', id),
  listProjectPackages: () => ipcRenderer.invoke('amazon:listProjectPackages'),
  exportProjectPackage: (projectId) => ipcRenderer.invoke('amazon:exportProjectPackage', projectId),
  importProjectPackage: (filePath) => ipcRenderer.invoke('amazon:importProjectPackage', filePath),
  approveAction: (id) => ipcRenderer.invoke('amazon:approveAction', id),
  rejectAction: (id) => ipcRenderer.invoke('amazon:rejectAction', id),
  executeApprovedAction: (id) => ipcRenderer.invoke('amazon:executeApprovedAction', id),
  listProviderProfiles: () => ipcRenderer.invoke('amazon:listProviderProfiles'),
  saveProviderProfile: (payload) => ipcRenderer.invoke('amazon:saveProviderProfile', payload),
  deleteProviderProfile: (id, force = false) => ipcRenderer.invoke('amazon:deleteProviderProfile', id, force),
  testProviderProfile: (id) => ipcRenderer.invoke('amazon:testProviderProfile', id),
  listProviderRoutes: () => ipcRenderer.invoke('amazon:listProviderRoutes'),
  saveProviderRoute: (payload) => ipcRenderer.invoke('amazon:saveProviderRoute', payload),
  listAgents: () => ipcRenderer.invoke('amazon:listAgents'),
  saveAgent: (payload) => ipcRenderer.invoke('amazon:saveAgent', payload),
  deleteAgent: (id) => ipcRenderer.invoke('amazon:deleteAgent', id),
  listAgentFlows: () => ipcRenderer.invoke('amazon:listAgentFlows'),
  saveAgentFlow: (payload) => ipcRenderer.invoke('amazon:saveAgentFlow', payload),
  publishAgentFlow: (id) => ipcRenderer.invoke('amazon:publishAgentFlow', id),
  listWorkflowRuns: () => ipcRenderer.invoke('amazon:listWorkflowRuns'),
  getWorkflowRun: (id) => ipcRenderer.invoke('amazon:getWorkflowRun', id),
  submitWorkflowRun: (payload) => ipcRenderer.invoke('amazon:submitWorkflowRun', payload),
  listMediaOperations: () => ipcRenderer.invoke('amazon:listMediaOperations'),
  listMediaRuns: () => ipcRenderer.invoke('amazon:listMediaRuns'),
  getMediaRun: (id) => ipcRenderer.invoke('amazon:getMediaRun', id),
  submitMediaRun: (payload) => ipcRenderer.invoke('amazon:submitMediaRun', payload),
  cancelMediaRun: (id) => ipcRenderer.invoke('amazon:cancelMediaRun', id),
  deleteMediaRun: (id) => ipcRenderer.invoke('amazon:deleteMediaRun', id),
  listVerificationResults: (filters = {}) => ipcRenderer.invoke('amazon:listVerificationResults', filters),
  getUsageSummary: (filters = {}) => ipcRenderer.invoke('amazon:getUsageSummary', filters),
  listAssets: (filters = {}) => ipcRenderer.invoke('amazon:listAssets', filters),
  importAssets: (payload) => ipcRenderer.invoke('amazon:importAssets', payload),
  uploadAssets: (payload) => ipcRenderer.invoke('amazon:uploadAssets', payload),
  getAsset: (assetId) => ipcRenderer.invoke('amazon:getAsset', assetId),
  deleteAsset: (assetId) => ipcRenderer.invoke('amazon:deleteAsset', assetId),
  selectAssetFiles: () => ipcRenderer.invoke('amazon:selectAssetFiles'),
  listAssistantMessages: () => ipcRenderer.invoke('amazon:listAssistantMessages'),
  submitAssistantMessage: (payload) => ipcRenderer.invoke('amazon:submitAssistantMessage', payload),
  codexStatus: () => ipcRenderer.invoke('amazon:codexStatus'),
  submitCodexTask: (payload) => ipcRenderer.invoke('amazon:submitCodexTask', payload),
  openPath: (filePath) => ipcRenderer.invoke('amazon:openPath', filePath),
  getPathForFile: (file) => webUtils.getPathForFile(file)
});
